name: main
on:
  push:
    branches:
      - main  
jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir release && cp target/users-api-*.jar release
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: release

  delivery:
    runs-on: ubuntu-latest
    needs: [build_and_release]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure Container Registry        
        run: docker login ${{ secrets.REGISTRY_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} 
      - name: Build Container image
        run: docker build -t ${{ secrets.REGISTRY_SERVER }}/usersapichallenge:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.REGISTRY_SERVER }}/usersapichallenge:latest              
