name: main
on:
  push:
    branches:
      - main  
jobs:
  build_and_release_:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir release && cp target/users-api-*.jar release
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: release

  delivery:
    name: Delivery to Azure Registry
    runs-on: ubuntu-latest
    needs: [build_and_release_]
    steps:      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build .t ${{ secrets.REGISTRY_SERVER }}/usersapichallenge:latest
          docker push ${{ secrets.REGISTRY_SERVER }}/usersapichallenge:latest
